---
- hosts: all
  tasks:
    # NOTE(yoctozepto): devstack starts WSGI-based, API services too early
    # to make post-config apply to them
    # see: https://bugs.launchpad.net/devstack/+bug/1860287
    - name: "Restart devstack API services"
      command: "systemctl restart devstack@{{ item }}"
      become: True
      loop:
        - keystone
        - g-api
        - q-svc
        - n-api
