---
- hosts: all
  roles:
    - ensure-javascript-build-tool
    - nodejs-test-dependencies
  tasks:
    # NOTE(yoctozepto): nodejs-test-dependencies role installs only
    # chromium-browser but we need firefox too
    - name: Install firefox
      apt:
        name: firefox
      become: true
